name: Cargo Test Suite

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: ./test.sh